apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  type: LoadBalancer
  selector:
    app: cluster-demo
  ports:
  - name: web
    port: 80    
    targetPort: 8080
    nodePort: 30080