apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
  labels:
    app: cluster-demo
spec:
  securityContext:
    runAsUser: 1000
    fsGroup: 1000     
  containers:
  - name: py-server-demo
    image: payara/server-cluster-demo
    imagePullPolicy: Never
    resources:
      limits:
        memory: "1024M"
        cpu: "2"
    ports:
      - containerPort: 8080